session_name: AxisEngine
windows:
  - window_name: editor-project
    shell_command_before:
      - cd ~/Developer/BocanOnline/AxisEngine/
      - nvim
  - window_name: shell
    shell_command_before:
      - cd ~/Developer/BocanOnline/AxisEngine/
  - window_name: agent
    shell_command_before:
      - cd ~/Developer/BocanOnline/AxisEngine/
      - opencode
